image:
  repository: linuxserver/nzbget
  pullPolicy: IfNotPresent
  tag: version-v21.1

service:
  main:
    ports:
      main:
        port: 10057
        targetPort: 6789

probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

  startup:
    enabled: false

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
